<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--Dimensions-->
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <!--Masses-->
    <xacro:property name="base_mass" value="5.0" />
    <xacro:property name="wheel_mass" value="0.5" />
    <xacro:property name="caster_mass" value="0.2" />

    <!--Inertia-->
    <xacro:macro name="inertial_box" params="mass x y z">
        <inertial>
            <mass value="${mass}" />
            <origin xyz="0 0 ${z/2.0}" rpy="0 0 0"/>
            <inertia
                ixx="${(1.0/12.0) * mass * (y*y + z*z)}"
                iyy="${(1.0/12.0) * mass * (x*x + z*z)}"
                izz="${(1.0/12.0) * mass * (x*x + y*y)}"
                ixy="0.0" ixz="0.0" iyz="0.0" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="inertial_cylinder" params="mass radius length">
        <inertial>
            <mass value="${mass}" />
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
            <inertia
                ixx="${(1.0/12.0)*mass*(3*radius*radius + length*length)}"
                iyy="${(1.0/2.0)*mass*radius*radius}"
                izz="${(1.0/12.0)*mass*(3*radius*radius + length*length)}"
                ixy="0.0" ixz="0.0" iyz="0.0" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="inertial_sphere" params="mass radius">
        <inertial>
            <mass value="${mass}" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia
                ixx="${(2.0/5.0)*mass*radius*radius}"
                iyy="${(2.0/5.0)*mass*radius*radius}"
                izz="${(2.0/5.0)*mass*radius*radius}"
                ixy="0.0" ixz="0.0" iyz="0.0" />
        </inertial>
    </xacro:macro>

    <!--Links-->
    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>

        <xacro:inertial_box mass="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}" />
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>

            <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_length}" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>

         <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>

        <xacro:inertial_sphere mass="${caster_mass}" radius="${wheel_radius / 2.0}" />
    </link>

    <!--Joints-->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_length / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
    </joint>

</robot>